import fs from "node:fs/promises";
import pdf from "pdf-parse-new";
import { ValidationError } from "../../utils/errors.js";

/**
 * Clean up the raw extracted text:
 * - normalize line endings (Windows / old-Mac → \n)
 * - trim trailing (and excessive leading) whitespace per line
 * - preserve meaningful line breaks and bullet glyphs
 * - collapse runs of blank lines so structure stays readable
 *
 * Lines are kept as separate lines — headings and list bullets are intentionally
 * not merged, so document structure remains understandable.
 */
function cleanText(raw) {
  const lines = raw
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .split("\n")
    .map((line) => line.trimEnd());

  const result = [];
  let previousWasBlank = true;
  for (const line of lines) {
    const isBlank = line.trim() === "";
    if (isBlank && previousWasBlank) {
      // skip consecutive blank lines (collapse them into a single separator)
      continue;
    }
    result.push(line);
    previousWasBlank = isBlank;
  }

  return result.join("\n").trim();
}

/**
 * Extract plain text from a PDF file on disk.
 *
 * @param {string} filePath - Absolute path to the uploaded PDF (generated by the upload middleware).
 * @returns {Promise<string>} The cleaned, extracted text of the PDF.
 */
export async function extractTextFromPdf(filePath) {
  if (!filePath || typeof filePath !== "string") {
    throw new ValidationError("A valid PDF file path is required.");
  }

  let data;
  try {
    const buffer = await fs.readFile(filePath);
    data = await pdf(buffer);
  } catch (error) {
    throw new ValidationError(
      "Could not read the PDF. The file may be corrupted or not a valid PDF.",
    );
  }

  const text = cleanText(data?.text ?? "");

  // No OCR at this stage: a PDF without extractable text is reported clearly
  // instead of silently returning an empty body.
  if (!text) {
    throw new ValidationError(
      "No extractable text found in the PDF. It may be a scanned document or contain an embedded font that blocks text extraction.",
    );
  }

  return text;
}
